name: Update README with Advent of Code Progress

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 4296036
          sessionCookie: ${{ secrets.AOC_SESSION }}
          leaderboardId: ${{ secrets.AOC_LEADERBOARD }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README with latest Advent of Code progress
